/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package biblioteca.interfac;

import biblioteca.servicos.BaseDeDados;
import javax.swing.JOptionPane;

/**
 *
 * @author Paulo Afonso
 */
public class CadastrarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form Autor
     */
    public CadastrarUsuario() {
        initComponents();
        txtUsuario.setDocument(new BaseDeDados(50, BaseDeDados.TipoEntrada.NOME));
        txtCPF.setDocument(new BaseDeDados(11, BaseDeDados.TipoEntrada.CPF));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEntrar = new javax.swing.JButton();
        lblCPF1 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        lblCadastro = new javax.swing.JLabel();
        lblFundoCadastro = new javax.swing.JLabel();
        lblPainelBiblioteca = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, -1, -1));

        lblCPF1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCPF1.setForeground(new java.awt.Color(255, 255, 255));
        lblCPF1.setText("Faça o cadastro para continuar");
        getContentPane().add(lblCPF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        txtCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPFActionPerformed(evt);
            }
        });
        getContentPane().add(txtCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 140, -1));

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 140, -1));

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("Usuario");
        getContentPane().add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        lblCPF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCPF.setForeground(new java.awt.Color(255, 255, 255));
        lblCPF.setText("CPF");
        getContentPane().add(lblCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        lblCadastro.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblCadastro.setForeground(new java.awt.Color(255, 255, 255));
        lblCadastro.setText("Cadastro");
        getContentPane().add(lblCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));

        lblFundoCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblioteca/imagens/FundoLogin_1.png"))); // NOI18N
        getContentPane().add(lblFundoCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 120, 560, 270));

        lblPainelBiblioteca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblioteca/imagens/painelbiblioteca.jpg"))); // NOI18N
        getContentPane().add(lblPainelBiblioteca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPFActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        String nome = txtUsuario.getText();
        String cpf = txtCPF.getText();
        if(nome.isEmpty() ||  cpf.isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha os campos!");
        }else{
            MenuPrincipal M = new MenuPrincipal();
            M.setVisible(true);
            CadastrarUsuario cad = new CadastrarUsuario();
            
            cad.setVisible(false);
        }
        
    }//GEN-LAST:event_btnEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCPF1;
    private javax.swing.JLabel lblCadastro;
    private javax.swing.JLabel lblFundoCadastro;
    private javax.swing.JLabel lblPainelBiblioteca;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
