/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package biblioteca.interfac;

import biblioteca.servicos.BaseDeDados;
import java.awt.event.KeyEvent;

/**
 *
 * @author Paulo Afonso
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        
        PainelCadastro.setVisible(false);
        PainelLivrosCadastrados.setVisible(false);
        txtTitulo.setDocument(new BaseDeDados(20, BaseDeDados.TipoEntrada.TITULO));
        txtAutor.setDocument(new BaseDeDados(50, BaseDeDados.TipoEntrada.AUTOR));
        txtCodigoLivro.setDocument(new BaseDeDados(15, BaseDeDados.TipoEntrada.CODIGO));
        txtAnoLancamento.setDocument(new BaseDeDados(4, BaseDeDados.TipoEntrada.ANO));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelLivrosCadastrados = new javax.swing.JPanel();
        Fechar2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        PainelCadastro = new javax.swing.JPanel();
        Fechar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtAnoLancamento = new javax.swing.JTextField();
        txtCodigoLivro = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        lblFundoMenu = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuICadastrarLivro = new javax.swing.JMenuItem();
        jMenulLivrosCadastrados = new javax.swing.JMenuItem();
        jMenuPesquisas = new javax.swing.JMenu();
        jMenuIPesquisarLivros = new javax.swing.JMenuItem();
        jMenuIConsultarUsuario = new javax.swing.JMenuItem();
        jMenuILivroEmprestado = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenulEmprestimos = new javax.swing.JMenu();
        jMenuICadastrarEmprestimo = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PainelLivrosCadastrados.setBackground(new java.awt.Color(204, 204, 204));
        PainelLivrosCadastrados.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        PainelLivrosCadastrados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PainelLivrosCadastradosKeyPressed(evt);
            }
        });

        Fechar2.setBackground(new java.awt.Color(255, 0, 0));
        Fechar2.setText("X");
        Fechar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fechar2ActionPerformed(evt);
            }
        });

        jTable2.setBackground(new java.awt.Color(153, 153, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Livros Cadastrados"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setToolTipText("");
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout PainelLivrosCadastradosLayout = new javax.swing.GroupLayout(PainelLivrosCadastrados);
        PainelLivrosCadastrados.setLayout(PainelLivrosCadastradosLayout);
        PainelLivrosCadastradosLayout.setHorizontalGroup(
            PainelLivrosCadastradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
            .addGroup(PainelLivrosCadastradosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Fechar2))
        );
        PainelLivrosCadastradosLayout.setVerticalGroup(
            PainelLivrosCadastradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLivrosCadastradosLayout.createSequentialGroup()
                .addComponent(Fechar2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(PainelLivrosCadastrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 450, 350));

        PainelCadastro.setBackground(new java.awt.Color(204, 204, 204));
        PainelCadastro.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        Fechar.setBackground(new java.awt.Color(255, 0, 0));
        Fechar.setText("X");
        Fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitulo.setText("Título");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Nome do Autor");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Código do livro");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Ano de lançamento");

        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });
        txtTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTituloKeyPressed(evt);
            }
        });

        txtAnoLancamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnoLancamentoActionPerformed(evt);
            }
        });
        txtAnoLancamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAnoLancamentoKeyPressed(evt);
            }
        });

        txtCodigoLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoLivroActionPerformed(evt);
            }
        });
        txtCodigoLivro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoLivroKeyPressed(evt);
            }
        });

        txtAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAutorActionPerformed(evt);
            }
        });
        txtAutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAutorKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout PainelCadastroLayout = new javax.swing.GroupLayout(PainelCadastro);
        PainelCadastro.setLayout(PainelCadastroLayout);
        PainelCadastroLayout.setHorizontalGroup(
            PainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelCadastroLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Fechar))
            .addGroup(PainelCadastroLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(PainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PainelCadastroLayout.createSequentialGroup()
                        .addGroup(PainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PainelCadastroLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(193, 193, 193))
                            .addGroup(PainelCadastroLayout.createSequentialGroup()
                                .addComponent(lblTitulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34))
                    .addGroup(PainelCadastroLayout.createSequentialGroup()
                        .addGroup(PainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtAnoLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PainelCadastroLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(58, 58, 58)
                                .addComponent(txtCodigoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PainelCadastroLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        PainelCadastroLayout.setVerticalGroup(
            PainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCadastroLayout.createSequentialGroup()
                .addComponent(Fechar)
                .addGap(39, 39, 39)
                .addGroup(PainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(PainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(PainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCodigoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(PainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAnoLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        getContentPane().add(PainelCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 450, 350));

        lblFundoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblioteca/imagens/MenuBiblioteca.jpg"))); // NOI18N
        getContentPane().add(lblFundoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 902, 569));

        jMenuCadastros.setText("Cadastros");

        jMenuICadastrarLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblioteca/imagens/icones/iconlivro.png"))); // NOI18N
        jMenuICadastrarLivro.setText("Cadastrar Livro");
        jMenuICadastrarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuICadastrarLivroActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuICadastrarLivro);

        jMenulLivrosCadastrados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblioteca/imagens/icones/book.png"))); // NOI18N
        jMenulLivrosCadastrados.setText("Livros Cadastrados");
        jMenulLivrosCadastrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenulLivrosCadastradosActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenulLivrosCadastrados);

        jMenuBar1.add(jMenuCadastros);

        jMenuPesquisas.setText("Pesquisas");

        jMenuIPesquisarLivros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblioteca/imagens/icones/loupe.png"))); // NOI18N
        jMenuIPesquisarLivros.setText("Pesquisar Livros");
        jMenuPesquisas.add(jMenuIPesquisarLivros);

        jMenuIConsultarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblioteca/imagens/icones/cliente-icon.png"))); // NOI18N
        jMenuIConsultarUsuario.setText("Consultar Usuário");
        jMenuPesquisas.add(jMenuIConsultarUsuario);

        jMenuILivroEmprestado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblioteca/imagens/icones/manual.png"))); // NOI18N
        jMenuILivroEmprestado.setText("Consultar Livros Emprestados");
        jMenuILivroEmprestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuILivroEmprestadoActionPerformed(evt);
            }
        });
        jMenuPesquisas.add(jMenuILivroEmprestado);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblioteca/imagens/icones/e-book.png"))); // NOI18N
        jMenuItem1.setText("Consultar Livros Disponíveis");
        jMenuPesquisas.add(jMenuItem1);

        jMenuBar1.add(jMenuPesquisas);

        jMenulEmprestimos.setText("Empréstimos");

        jMenuICadastrarEmprestimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblioteca/imagens/icones/book (1).png"))); // NOI18N
        jMenuICadastrarEmprestimo.setText("Cadastrar Empréstimo");
        jMenulEmprestimos.add(jMenuICadastrarEmprestimo);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblioteca/imagens/icones/book (2).png"))); // NOI18N
        jMenuItem3.setText("Finalizar Empréstimo");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenulEmprestimos.add(jMenuItem3);

        jMenuBar1.add(jMenulEmprestimos);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuILivroEmprestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuILivroEmprestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuILivroEmprestadoActionPerformed

    private void jMenuICadastrarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuICadastrarLivroActionPerformed
       PainelCadastro.setVisible(true);
    }//GEN-LAST:event_jMenuICadastrarLivroActionPerformed

    private void FecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharActionPerformed
        PainelCadastro.setVisible(false);
    }//GEN-LAST:event_FecharActionPerformed

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void txtAnoLancamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnoLancamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnoLancamentoActionPerformed

    private void txtAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutorActionPerformed

    private void txtCodigoLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoLivroActionPerformed

    private void Fechar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fechar2ActionPerformed
       PainelLivrosCadastrados.setVisible(false);
    }//GEN-LAST:event_Fechar2ActionPerformed

    private void jMenulLivrosCadastradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenulLivrosCadastradosActionPerformed
        PainelLivrosCadastrados.setVisible(true);
    }//GEN-LAST:event_jMenulLivrosCadastradosActionPerformed

    private void PainelLivrosCadastradosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PainelLivrosCadastradosKeyPressed
        
    }//GEN-LAST:event_PainelLivrosCadastradosKeyPressed

    private void txtAutorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAutorKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            txtCodigoLivro.requestFocus();
        }
    }//GEN-LAST:event_txtAutorKeyPressed

    private void txtAnoLancamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnoLancamentoKeyPressed
        
    }//GEN-LAST:event_txtAnoLancamentoKeyPressed

    private void txtTituloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTituloKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            txtAutor.requestFocus();
        }
    }//GEN-LAST:event_txtTituloKeyPressed

    private void txtCodigoLivroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoLivroKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            txtAnoLancamento.requestFocus();
        }
    }//GEN-LAST:event_txtCodigoLivroKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Fechar;
    private javax.swing.JButton Fechar2;
    private javax.swing.JPanel PainelCadastro;
    private javax.swing.JPanel PainelLivrosCadastrados;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenuItem jMenuICadastrarEmprestimo;
    private javax.swing.JMenuItem jMenuICadastrarLivro;
    private javax.swing.JMenuItem jMenuIConsultarUsuario;
    private javax.swing.JMenuItem jMenuILivroEmprestado;
    private javax.swing.JMenuItem jMenuIPesquisarLivros;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu jMenuPesquisas;
    private javax.swing.JMenu jMenulEmprestimos;
    private javax.swing.JMenuItem jMenulLivrosCadastrados;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblFundoMenu;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtAnoLancamento;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtCodigoLivro;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
